### ISSUE TITLE
Unable to produce training process with missing dataset files.

### ISSUE THREAD

**Issue by tongda** [lyhisme/DeST#1]
Hi,

An interesting method on skelaton-based action segmentation! Good work!

According to README, dataset dir looks like this:

```
├─ dataset
|   |-- MCFS-130
|   |   |-- features/
│   |   |-- groundTruth/
│   |   |-- gt_arr/
│   |   |-- gt_boundary_arr/
│   |   |-- splits/
|   |   |-- mapping.txt
```

But downloaded dataset does not have gt_arr and gt_boundary_arr sub dirs. How to generate these files, please?

**Comment by tongda** [comment]
My bad, I found the scripts in `scripts/experiment.sh`.

**Comment by lyhisme** [comment]
> Hi,
> 
> An interesting method on skelaton-based action segmentation! Good work!
> 
> According to README, dataset dir looks like this:
> 
> ```
> ├─ dataset
> |   |-- MCFS-130
> |   |   |-- features/
> │   |   |-- groundTruth/
> │   |   |-- gt_arr/
> │   |   |-- gt_boundary_arr/
> │   |   |-- splits/
> |   |   |-- mapping.txt
> ```
> 
> But downloaded dataset does not have gt_arr and gt_boundary_arr sub dirs. How to generate these files, please?

Thanks for your attention to our work. I rechecked the [[Datasets](https://github.com/lyhisme/DeST/tree/main#Datasets)] and it contains all the files. If you want to use your own data, you can follow the code in `scripts/experiment.sh` to generate the corresponding data.
